name: ConvertToJsFromTs

on:
  push:
    branches: [test]

jobs:
  CodeToDist:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Install dependencies
        run: |
            cd verletjs
            npm ci

      - name: Compile TypeScript
        run: |
            cd verletjs
            npx tsc

      - name: Compile TypeScript
        run: |
            cd verletjs
            npx tsc

      - name: Upload dist as artifact
        uses: actions/upload-artifact@v4
        with:
            name: dist
            path: verletjs/dist
